/* ------------------------------------------------------------------
   Application Route Classification Matrix & SEO Copywriting Registry
------------------------------------------------------------------- */

export interface AppRoute {
  path: string;
  indexable: boolean;
  rendering: "SSG" | "CSR" | "Static";
  changefreq?: "always" | "hourly" | "daily" | "weekly" | "monthly" | "yearly" | "never";
  priority?: number;
  primaryIntent: string;
  primaryKeyword: string;
  secondaryTopics: string[];
  h1: string;
  title: string;
  description: string;
  ogTitle: string;
  ogDescription: string;
  breadcrumbName?: string;
}

export const routes: AppRoute[] = [
  {
    path: "/",
    indexable: true,
    rendering: "SSG",
    changefreq: "weekly",
    priority: 1.0,
    primaryIntent: "Navigational & Brand Proposition",
    primaryKeyword: "best IPTV service 2026",
    secondaryTopics: [
      "4K live sports streaming",
      "anti-freeze server technology",
      "24h free trial",
      "25,000 live channels",
      "VOD library",
    ],
    h1: "Best IPTV Service in 2026",
    title: "Teleview | 2026 Best IPTV Service With 24h Free Trial",
    description:
      "Stream live sports, international news, and 4K entertainment worldwide. Teleview offers ultra-fast streaming servers, 24/7 support, and no long-term contracts.",
    ogTitle: "Teleview | 2026 Best IPTV Service With 24h Free Trial",
    ogDescription:
      "Experience buffer-free 4K live sports and international television across all your devices with 24/7 dedicated subscriber support.",
    breadcrumbName: "Home",
  },
  {
    path: "/setup",
    indexable: true,
    rendering: "SSG",
    changefreq: "monthly",
    priority: 0.8,
    primaryIntent: "Informational How-To & Technical Installation",
    primaryKeyword: "IPTV setup guide",
    secondaryTopics: [
      "Firestick installation",
      "Smart TV setup",
      "Xtream Codes API",
      "M3U playlist URL",
      "TiviMate configuration",
    ],
    h1: "IPTV Setup & Installation Guide",
    title: "IPTV Setup & Installation Guide | Teleview",
    description:
      "Step-by-step setup instructions for Teleview on Amazon Firestick, Android TV, Smart TVs, Apple iOS, and MAG boxes. Configure Xtream Codes or M3U in minutes.",
    ogTitle: "How to Set Up Teleview on Firestick, Smart TV, & Mobile",
    ogDescription:
      "Step-by-step installation guides with verified configuration steps for TiviMate, IPTV Smarters, and Smart TV players.",
    breadcrumbName: "Setup & Installation",
  },
  {
    path: "/devices",
    indexable: true,
    rendering: "SSG",
    changefreq: "monthly",
    priority: 0.8,
    primaryIntent: "Commercial Investigation & Hardware Compatibility",
    primaryKeyword: "supported IPTV devices and apps",
    secondaryTopics: [
      "hardware specifications",
      "Fire TV Stick",
      "Android TV boxes",
      "Apple TV 4K",
      "Smart TV webOS & Tizen",
      "recommended IPTV players",
    ],
    h1: "Supported IPTV Devices & Apps",
    title: "Supported IPTV Devices & Apps | Teleview",
    description:
      "Explore compatible hardware and streaming apps for Teleview. Check minimum specs, RAM recommendations, and recommended players for Fire TV, Android, and Smart TVs.",
    ogTitle: "Supported Streaming Devices & Hardware Specs | Teleview",
    ogDescription:
      "Check device compatibility, recommended hardware requirements, and supported video codecs for smooth 4K streaming.",
    breadcrumbName: "Supported Devices",
  },
  {
    path: "/faq",
    indexable: true,
    rendering: "SSG",
    changefreq: "monthly",
    priority: 0.8,
    primaryIntent: "Informational & Pre-Purchase Inquiry",
    primaryKeyword: "IPTV frequently asked questions",
    secondaryTopics: [
      "internet speed requirements",
      "free trial activation",
      "device concurrency limits",
      "VPN usage rules",
      "satisfaction guarantee",
    ],
    h1: "Frequently Asked Questions & Support",
    title: "IPTV Frequently Asked Questions & Support | Teleview",
    description:
      "Find clear answers to common questions about Teleview subscriptions, activation speed, internet bandwidth requirements, VPN compatibility, and refunds.",
    ogTitle: "Frequently Asked Questions & Answers | Teleview Support",
    ogDescription:
      "Everything you need to know about Teleview: bandwidth requirements, free trials, multi-device rules, and technical support.",
    breadcrumbName: "FAQ & Support",
  },
  {
    path: "/iptv-subscription",
    indexable: true,
    rendering: "SSG",
    changefreq: "weekly",
    priority: 0.9,
    primaryIntent: "Commercial Comparison & Duration Selection",
    primaryKeyword: "IPTV subscription plans",
    secondaryTopics: [
      "tier comparison",
      "duration discounts",
      "multi-device connections",
      "14-day refund guarantee",
      "4K sports channels",
    ],
    h1: "IPTV Subscription Plans & Pricing",
    title: "IPTV Subscription – Plans & Pricing | Teleview",
    description:
      "Compare flexible Teleview IPTV subscription packages from 1 month to 1 year. Instant activation, 4K streaming, 25,000+ channels, and 14-day money-back guarantee.",
    ogTitle: "Compare Teleview IPTV Subscription Plans & Pricing",
    ogDescription:
      "Find the best streaming plan for your home. Compare 1, 3, 6, and 12-month packages with instant activation and verified 4K sports coverage.",
    breadcrumbName: "IPTV Subscription",
  },
  {
    path: "/iptv-subscription/1-month",
    indexable: true,
    rendering: "SSG",
    changefreq: "weekly",
    priority: 0.85,
    primaryIntent: "Commercial & Short-Term Flexibility",
    primaryKeyword: "1 month IPTV subscription",
    secondaryTopics: [
      "$16 monthly plan",
      "no commitment streaming",
      "instant activation",
      "sports event pass",
      "full channel lineup",
    ],
    h1: "1 Month IPTV Subscription",
    title: "1 Month IPTV Subscription – $16 | Teleview",
    description:
      "Get a 1 month IPTV subscription for $16. Enjoy full access to 25,000+ live channels, 4K sports, and 120k+ movies with instant activation and zero contracts.",
    ogTitle: "1 Month IPTV Subscription for $16 – Instant Activation | Teleview",
    ogDescription:
      "Flexible monthly streaming without locked-in contracts. Full live sports and entertainment access with 24/7 technical support.",
    breadcrumbName: "1 Month",
  },
  {
    path: "/iptv-subscription/3-months",
    indexable: true,
    rendering: "SSG",
    changefreq: "weekly",
    priority: 0.85,
    primaryIntent: "Commercial & Quarterly Value",
    primaryKeyword: "3 months IPTV subscription",
    secondaryTopics: [
      "$39 quarterly package",
      "$13 per month rate",
      "19% cost savings",
      "sports tournament coverage",
      "continuous playlist",
    ],
    h1: "3 Months IPTV Subscription",
    title: "3 Months IPTV Subscription – $39 ($13/mo) | Teleview",
    description:
      "Save 19% with a 3 month IPTV subscription for $39 ($13.00/mo). Stream 25,000+ live channels, 4K sports leagues, and on-demand movies with dedicated support.",
    ogTitle: "3 Months IPTV Subscription – Save 19% at $13/mo | Teleview",
    ogDescription:
      "Quarterly flexibility at $13.00/month. Stream international tournaments and series without monthly renewal friction.",
    breadcrumbName: "3 Months",
  },
  {
    path: "/iptv-subscription/6-months",
    indexable: true,
    rendering: "SSG",
    changefreq: "weekly",
    priority: 0.85,
    primaryIntent: "Commercial & Semi-Annual Value",
    primaryKeyword: "6 months IPTV subscription",
    secondaryTopics: [
      "$60 semi-annual plan",
      "$10 per month rate",
      "37.5% cost savings",
      "priority server routing",
      "multi-device streaming",
    ],
    h1: "6 Months IPTV Subscription",
    title: "6 Months IPTV Subscription – $60 ($10/mo) | Teleview",
    description:
      "Save 37.5% with a 6 month IPTV subscription for $60 ($10.00/mo). Get 25,000+ channels, 4K sports, VOD library, and 99.9% uptime on all your devices.",
    ogTitle: "6 Months IPTV Subscription for $60 – $10/mo Semi-Annual Value | Teleview",
    ogDescription:
      "Half a year of uninterrupted 4K sports and worldwide channels at 37.5% off standard monthly rates.",
    breadcrumbName: "6 Months",
  },
  {
    path: "/iptv-subscription/12-months",
    indexable: true,
    rendering: "SSG",
    changefreq: "weekly",
    priority: 0.85,
    primaryIntent: "Commercial & Maximum Annual Savings",
    primaryKeyword: "12 months IPTV subscription",
    secondaryTopics: [
      "$90 annual plan",
      "$7.50 per month rate",
      "save $102",
      "dedicated server priority",
      "annual entertainment pass",
    ],
    h1: "12 Months IPTV Subscription",
    title: "12 Months IPTV Subscription – $90 ($7.50/mo) | Teleview",
    description:
      "Get a 12 month IPTV subscription for $90 ($7.50/mo). Save $102 with 25,000+ live channels, 4K sports, VOD library, dedicated server priority, and no contracts.",
    ogTitle: "12 Months IPTV Subscription – Best Value at $7.50/Month | Teleview",
    ogDescription:
      "Maximize your savings with a full year of premium television for $90. Includes dedicated server priority and 24/7 customer support.",
    breadcrumbName: "12 Months",
  },
  {
    path: "/pricing",
    indexable: false,
    rendering: "Static",
    primaryIntent: "Commercial Redirect Alias",
    primaryKeyword: "IPTV pricing",
    secondaryTopics: ["subscription pricing", "plan costs", "channel packages"],
    h1: "IPTV Subscription Plans & Pricing",
    title: "IPTV Subscription Plans & Pricing | Teleview",
    description:
      "Compare Teleview IPTV subscription plans. Get 25,000+ live channels, 4K sports, and 120k+ movies from $7.50/mo. Fast activation and 14-day guarantee.",
    ogTitle: "Teleview IPTV Pricing & Subscription Packages",
    ogDescription:
      "Compare all IPTV subscription tiers and pricing options from $7.50/mo.",
    breadcrumbName: "Plans & Pricing",
  },
  {
    path: "/contact",
    indexable: true,
    rendering: "SSG",
    changefreq: "monthly",
    priority: 0.8,
    primaryIntent: "Support & Customer Service Inquiries",
    primaryKeyword: "contact Teleview support",
    secondaryTopics: [
      "WhatsApp live chat",
      "email ticketing desk",
      "activation assistance",
      "24/7 customer service",
    ],
    h1: "Contact Teleview Support",
    title: "Contact Teleview Support | 24/7 Customer Assistance",
    description:
      "Contact Teleview customer support via WhatsApp or email. 24/7 technical assistance for activation, device setup, and subscription inquiries.",
    ogTitle: "Contact Teleview 24/7 Technical Support Desk",
    ogDescription:
      "Direct access to Teleview support agents for instant credential assistance, player setup help, and account renewals.",
    breadcrumbName: "Contact Us",
  },
  {
    path: "/terms-conditions",
    indexable: true,
    rendering: "SSG",
    changefreq: "monthly",
    priority: 0.6,
    primaryIntent: "Legal Agreement & Terms of Service",
    primaryKeyword: "Teleview terms and conditions",
    secondaryTopics: [
      "residential service agreement",
      "acceptable use policy",
      "device connection limits",
      "service availability",
    ],
    h1: "Terms & Conditions",
    title: "Terms & Conditions | Teleview IPTV",
    description:
      "Review the Teleview IPTV Terms and Conditions. Learn about our service usage terms, account rules, streaming performance, and subscriber obligations.",
    ogTitle: "Terms & Conditions of Service | Teleview",
    ogDescription:
      "Official terms of service governing subscriber agreements, residential streaming usage, and account policies.",
    breadcrumbName: "Terms & Conditions",
  },
  {
    path: "/privacy-policy",
    indexable: true,
    rendering: "SSG",
    changefreq: "monthly",
    priority: 0.6,
    primaryIntent: "Legal Compliance & Privacy Disclosure",
    primaryKeyword: "Teleview privacy policy",
    secondaryTopics: [
      "GDPR & CCPA compliance",
      "zero viewing logs",
      "TLS encryption",
      "personal data handling",
      "cookie practices",
    ],
    h1: "Privacy Policy",
    title: "Privacy Policy | Teleview IPTV",
    description:
      "Understand how Teleview protects your personal data and privacy. Learn what information we collect, how it is used, and your data protection rights.",
    ogTitle: "Privacy Policy & Data Protection Standards | Teleview",
    ogDescription:
      "Detailed disclosure on subscriber confidentiality, data minimization, and technical security protocols.",
    breadcrumbName: "Privacy Policy",
  },
  {
    path: "/refund-policy",
    indexable: true,
    rendering: "SSG",
    changefreq: "monthly",
    priority: 0.6,
    primaryIntent: "Legal Terms & Consumer Protection",
    primaryKeyword: "Teleview refund policy 14 day guarantee",
    secondaryTopics: [
      "14-day money-back guarantee",
      "refund eligibility criteria",
      "processing timeline",
      "technical support qualification",
    ],
    h1: "Refund Policy",
    title: "Refund Policy & 14-Day Guarantee | Teleview IPTV",
    description:
      "Read Teleview's official 14-day refund policy. Clear, transparent guidelines on satisfaction guarantees, eligibility, and how to request a refund.",
    ogTitle: "14-Day Refund Policy & Guarantee Terms | Teleview",
    ogDescription:
      "Transparent terms and step-by-step procedures for requesting a refund under our 14-day satisfaction guarantee.",
    breadcrumbName: "Refund Policy",
  },
  {
    path: "/disclaimer",
    indexable: true,
    rendering: "SSG",
    changefreq: "monthly",
    priority: 0.6,
    primaryIntent: "Legal Operational Notice & Technology Clarification",
    primaryKeyword: "Teleview legal disclaimer and technology notice",
    secondaryTopics: [
      "IPTV transmission technology",
      "third-party content aggregation",
      "trademark fair use",
      "subscriber jurisdiction",
    ],
    h1: "Legal Disclaimer",
    title: "Legal Disclaimer & Copyright Notice | Teleview IPTV",
    description:
      "Important legal information regarding Teleview IPTV streaming technology, intellectual property, third-party content, DMCA concerns, and compliance.",
    ogTitle: "Legal Disclaimer & Content Technology Notice | Teleview",
    ogDescription:
      "Notice on streaming protocols, third-party player application compatibility, and subscriber legal compliance.",
    breadcrumbName: "Legal Disclaimer",
  },
  {
    path: "/help-center",
    indexable: true,
    rendering: "SSG",
    changefreq: "monthly",
    priority: 0.8,
    primaryIntent: "Informational Troubleshooting & Diagnostic Knowledge Base",
    primaryKeyword: "IPTV troubleshooting and knowledge base",
    secondaryTopics: [
      "HTTP 401 error resolution",
      "HTTP 403 stream locks",
      "M3U timeout fixes",
      "ISP DNS blocking",
      "buffer cache optimization",
    ],
    h1: "Help Center",
    title: "Help Center & Knowledge Base | Teleview IPTV",
    description:
      "Explore comprehensive troubleshooting guides, buffer optimization techniques, and setup tutorials for Teleview IPTV service.",
    ogTitle: "Teleview Help Center & Streaming Troubleshooting Guides",
    ogDescription:
      "Step-by-step diagnostic solutions for buffering, stream timeouts, and connection errors.",
    breadcrumbName: "Help Center",
  },
  {
    path: "/my-account",
    indexable: false,
    rendering: "SSG",
    changefreq: "monthly",
    priority: 0.7,
    primaryIntent: "Transactional & Subscriber Self-Service",
    primaryKeyword: "teleview my account subscription portal",
    secondaryTopics: [
      "subscription status verification",
      "Xtream API retrieval",
      "M3U link renewal",
      "order ID lookup",
    ],
    h1: "My Account",
    title: "My Account & Subscription Status | Teleview IPTV",
    description:
      "Check your subscription status, retrieve Xtream API / M3U credentials, or renew your Teleview IPTV service online.",
    ogTitle: "My Account & Subscription Status | Teleview Self-Service",
    ogDescription:
      "Check your active IPTV line status, view expiration dates, and renew your service directly.",
    breadcrumbName: "My Account",
  },
  {
    path: "/dmca",
    indexable: true,
    rendering: "SSG",
    changefreq: "monthly",
    priority: 0.6,
    primaryIntent: "Legal Compliance & Copyright Notice",
    primaryKeyword: "Teleview DMCA notice and copyright policy",
    secondaryTopics: [
      "17 U.S.C. § 512",
      "designated copyright agent",
      "infringement notification",
      "takedown procedure",
      "repeat infringer policy",
    ],
    h1: "DMCA Notice",
    title: "DMCA Notice & Copyright Policy | Teleview IPTV",
    description:
      "Review Teleview's DMCA notice, copyright policies, infringement takedown procedures, and designated copyright agent information.",
    ogTitle: "DMCA Notice & Copyright Infringement Policy | Teleview",
    ogDescription:
      "Official intellectual property compliance, copyright policies, and takedown procedures for Teleview.",
    breadcrumbName: "DMCA Notice",
  },
  {
    path: "/best-iptv",
    indexable: true,
    rendering: "SSG",
    changefreq: "weekly",
    priority: 0.9,
    primaryIntent: "Commercial Investigation & IPTV Player Comparison",
    primaryKeyword: "best IPTV players",
    secondaryTopics: [
      "best IPTV apps",
      "IPTV player comparison",
      "TiviMate vs Smarters",
      "Smart TV IPTV players",
      "EPG guide players",
    ],
    h1: "Best IPTV Players & Apps",
    title: "Best IPTV Players & Apps in 2026 | Teleview",
    description:
      "Compare the best IPTV players in 2026. Verified features, platform compatibility, EPG performance, and setup guides for TiviMate, Smarters, and IBO Player.",
    ogTitle: "Best IPTV Players & Apps in 2026 | Comprehensive Comparison",
    ogDescription:
      "Detailed technical comparison of top IPTV player applications across Firestick, Android TV, Smart TVs, Apple iOS, and desktop computers.",
    breadcrumbName: "Best IPTV Players",
  },
  {
    path: "/what-is-iptv",
    indexable: true,
    rendering: "SSG",
    changefreq: "monthly",
    priority: 0.85,
    primaryIntent: "Informational & Technical Pillar Guide",
    primaryKeyword: "what is IPTV",
    secondaryTopics: [
      "IPTV technology explained",
      "how IPTV works",
      "IPTV vs cable vs satellite",
      "IPTV protocols HLS MPEG-TS",
      "Xtream Codes API",
    ],
    h1: "What Is IPTV? The Complete 2026 Technology Guide",
    title: "What Is IPTV? The Complete 2026 Streaming Technology Guide | Teleview",
    description:
      "Understand how Internet Protocol Television works, how it compares to legacy cable and satellite, core streaming protocols (HLS, MPEG-TS), and legal frameworks.",
    ogTitle: "What Is IPTV? The Complete 2026 Streaming Technology Guide",
    ogDescription:
      "Deep dive into IPTV architecture, transmission protocols, hardware requirements, and side-by-side comparison with cable, satellite, and OTT services.",
    breadcrumbName: "What Is IPTV?",
  },
  {
    path: "/iptv-players",
    indexable: true,
    rendering: "SSG",
    changefreq: "weekly",
    priority: 0.85,
    primaryIntent: "Commercial Investigation & Software Directory",
    primaryKeyword: "IPTV player apps directory",
    secondaryTopics: [
      "IPTV players for smart TV",
      "IPTV apps for Firestick",
      "TiviMate vs Smarters",
      "Xtream Codes player apps",
      "M3U playlist players",
    ],
    h1: "IPTV Players & Streaming Apps Directory",
    title: "IPTV Players & Streaming Apps Directory (2026) | Teleview",
    description:
      "Explore the directory of top IPTV players for Android TV, Firestick, Apple TV, and Smart TVs. Verified platform specs, protocol matrices, and setup manuals.",
    ogTitle: "IPTV Players & Streaming Apps Directory | Teleview",
    ogDescription:
      "Browse technical specifications, supported protocols, and installation guides for all major IPTV media players.",
    breadcrumbName: "IPTV Players",
  },
  {
    path: "/iptv-players/tivimate",
    indexable: true,
    rendering: "SSG",
    changefreq: "monthly",
    priority: 0.8,
    primaryIntent: "Informational & Technical App Guide",
    primaryKeyword: "TiviMate IPTV Player",
    secondaryTopics: [
      "TiviMate for Android TV",
      "TiviMate for Fire TV",
      "TiviMate setup",
      "TiviMate multi-view",
      "TiviMate EPG",
    ],
    h1: "TiviMate IPTV Player: Features, Setup & Compatibility",
    title: "TiviMate IPTV Player: Setup, Features & Compatible Devices | Teleview",
    description:
      "TiviMate IPTV Player guide for Android TV and Firestick. Learn about cable-box EPG grid setup, multi-view, buffer settings, and Xtream Codes configuration.",
    ogTitle: "TiviMate IPTV Player Guide: Features, Setup & Settings | Teleview",
    ogDescription:
      "Master TiviMate on Android TV and Firestick: step-by-step Xtream Codes setup, multi-view configuration, and buffer troubleshooting.",
    breadcrumbName: "TiviMate",
  },
  {
    path: "/iptv-players/iptv-smarters-pro",
    indexable: true,
    rendering: "SSG",
    changefreq: "monthly",
    priority: 0.8,
    primaryIntent: "Informational & Technical App Guide",
    primaryKeyword: "IPTV Smarters Pro",
    secondaryTopics: [
      "IPTV Smarters Pro setup",
      "IPTV Smarters Pro devices",
      "IPTV Smarters Pro player",
      "Smarters Player Lite iOS",
      "Xtream Codes login",
    ],
    h1: "IPTV Smarters Pro: Features, Setup & Supported Devices",
    title: "IPTV Smarters Pro: Setup, Features & Supported Devices | Teleview",
    description:
      "Complete guide to IPTV Smarters Pro across Android, iOS, Firestick, PC, and Mac. Learn how to log in with Xtream Codes API, configure subtitles, and resolve playback errors.",
    ogTitle: "IPTV Smarters Pro: Cross-Platform Setup & Configuration Guide",
    ogDescription:
      "Step-by-step instructions to configure IPTV Smarters Pro on mobile, TV, and PC with Xtream Codes API, VOD subtitles, and multi-screen mode.",
    breadcrumbName: "IPTV Smarters Pro",
  },
  {
    path: "/iptv-players/ibo-player",
    indexable: true,
    rendering: "SSG",
    changefreq: "monthly",
    priority: 0.8,
    primaryIntent: "Informational & Technical App Guide",
    primaryKeyword: "IBO Player",
    secondaryTopics: [
      "IBO Player IPTV",
      "IBO Player Samsung TV",
      "IBO Player LG TV",
      "IBO Player activation",
      "Device MAC and Key",
    ],
    h1: "IBO Player: Smart TV Setup, Features & Device Activation",
    title: "IBO Player: IPTV Setup & Compatible Smart TVs | Teleview",
    description:
      "Guide to installing and activating IBO Player on Samsung Tizen and LG webOS Smart TVs. Learn device MAC activation, web portal playlist upload, and streaming troubleshooting.",
    ogTitle: "IBO Player Smart TV Guide: Installation & Activation | Teleview",
    ogDescription:
      "Install IBO Player directly from Samsung or LG app stores. Connect M3U or Xtream Codes playlists via the web management portal with zero sideloading.",
    breadcrumbName: "IBO Player",
  },
  {
    path: "/iptv-players/smartone",
    indexable: true,
    rendering: "SSG",
    changefreq: "monthly",
    priority: 0.8,
    primaryIntent: "Informational & Technical App Guide",
    primaryKeyword: "SmartOne IPTV",
    secondaryTopics: [
      "SmartOne IPTV player",
      "SmartOne IPTV Samsung",
      "SmartOne IPTV LG",
      "SmartOne MAC activation",
      "Vidaa OS IPTV",
    ],
    h1: "SmartOne IPTV: Features, Setup & Smart TV Compatibility",
    title: "SmartOne IPTV: Setup, Features & Smart TV Installation | Teleview",
    description:
      "Explore SmartOne IPTV for LG webOS, Samsung Tizen, and Vidaa Smart TVs. Understand MAC address portal configuration, dual-playlist support, and remote number dialing.",
    ogTitle: "SmartOne IPTV Player: Setup & Features for Smart TVs | Teleview",
    ogDescription:
      "Step-by-step setup guide for SmartOne IPTV on LG, Samsung, and Vidaa TVs. Configure dual playlists and EPG time-shifts via web portal.",
    breadcrumbName: "SmartOne IPTV",
  },
  {
    path: "/iptv-players/gse-smart-iptv",
    indexable: true,
    rendering: "SSG",
    changefreq: "monthly",
    priority: 0.8,
    primaryIntent: "Informational & Technical App Guide",
    primaryKeyword: "GSE Smart IPTV",
    secondaryTopics: [
      "GSE Smart IPTV iPhone",
      "GSE Smart IPTV Apple TV",
      "GSE Smart IPTV setup",
      "XMLTV EPG",
      "iOS AirPlay streaming",
    ],
    h1: "GSE Smart IPTV: Features, Apple TV Setup & iOS Compatibility",
    title: "GSE Smart IPTV: Apple iOS, Apple TV Setup & Features | Teleview",
    description:
      "Technical guide to GSE Smart IPTV on iPhone, iPad, and Apple TV (tvOS). Learn how to import M3U playlists, configure XMLTV EPG sources, and use AirPlay screen casting.",
    ogTitle: "GSE Smart IPTV Guide: iOS & Apple TV Configuration | Teleview",
    ogDescription:
      "Master GSE Smart IPTV on Apple devices. Configure remote playlists, local web server M3U uploads, and XMLTV program guide sources.",
    breadcrumbName: "GSE Smart IPTV",
  },
  {
    path: "/iptv-players/vlc",
    indexable: true,
    rendering: "SSG",
    changefreq: "monthly",
    priority: 0.8,
    primaryIntent: "Informational & Technical App Guide",
    primaryKeyword: "VLC IPTV",
    secondaryTopics: [
      "VLC M3U playlist",
      "VLC IPTV player",
      "play IPTV with VLC",
      "network caching VLC",
      "inspect stream codecs",
    ],
    h1: "VLC Media Player for IPTV: M3U Setup & Stream Diagnostics",
    title: "VLC Media Player for IPTV: M3U Playback & Codec Setup | Teleview",
    description:
      "How to stream IPTV playlists with VLC Media Player on Windows, Mac, and Linux. Step-by-step M3U network stream opening, buffer adjustments, and codec analysis.",
    ogTitle: "VLC Media Player for IPTV: Setup, Playlists & Diagnostics",
    ogDescription:
      "Use VLC Media Player to test raw M3U streams, diagnose audio/video codecs, and adjust network caching on Windows, macOS, and Linux.",
    breadcrumbName: "VLC Media Player",
  },
  {
    path: "/iptv-players/ott-navigator",
    indexable: true,
    rendering: "SSG",
    changefreq: "monthly",
    priority: 0.8,
    primaryIntent: "Informational & Technical App Guide",
    primaryKeyword: "OTT Navigator IPTV",
    secondaryTopics: [
      "OTT Navigator IPTV player",
      "OTT Navigator Android TV",
      "OTT Navigator setup",
      "ExoPlayer vs VLC engine",
      "Studio mode PiP",
    ],
    h1: "OTT Navigator IPTV: Power-User Features, Decoders & Setup",
    title: "OTT Navigator IPTV: Features, Advanced Setup & Decoders | Teleview",
    description:
      "Deep-dive into OTT Navigator IPTV for Android TV and Google TV. Explore custom ExoPlayer/VLC decoders, Studio mode, PiP, multi-provider aggregation, and EPG offsets.",
    ogTitle: "OTT Navigator IPTV: Power-User Setup & Features Guide",
    ogDescription:
      "Configure OTT Navigator IPTV on Android TV: select hardware decoders, enable Studio Picture-in-Picture, and combine multiple provider playlists.",
    breadcrumbName: "OTT Navigator",
  },
  {
    path: "/devices/firestick",
    indexable: true,
    rendering: "SSG",
    changefreq: "monthly",
    priority: 0.8,
    primaryIntent: "Informational How-To & Device Installation",
    primaryKeyword: "IPTV on Firestick",
    secondaryTopics: [
      "Fire TV Stick 4K IPTV",
      "install Downloader Firestick",
      "TiviMate Firestick setup",
      "Firestick buffering fix",
      "Fire TV developer options",
    ],
    h1: "How to Set Up & Stream IPTV on Amazon Fire TV Stick",
    title: "How to Set Up & Stream IPTV on Amazon Firestick (2026) | Teleview",
    description:
      "Step-by-step guide to installing and streaming IPTV on Amazon Fire TV Stick Lite, 4K, and Max. Configure Downloader, install TiviMate, and optimize buffer settings.",
    ogTitle: "How to Set Up IPTV on Amazon Firestick | Complete 2026 Manual",
    ogDescription:
      "Complete Firestick setup walkthrough: install Downloader, sideload TiviMate or IPTV Smarters Pro, and configure 4K 60 FPS sports streaming.",
    breadcrumbName: "Amazon Firestick",
  },
  {
    path: "/devices/samsung-smart-tv",
    indexable: true,
    rendering: "SSG",
    changefreq: "monthly",
    priority: 0.8,
    primaryIntent: "Informational How-To & Device Installation",
    primaryKeyword: "IPTV on Samsung Smart TV",
    secondaryTopics: [
      "Samsung Tizen IPTV",
      "IBO Player Samsung TV",
      "SmartOne IPTV Samsung",
      "Samsung TV MAC address activation",
      "Samsung IPTV without Firestick",
    ],
    h1: "How to Set Up & Stream IPTV on Samsung Smart TV",
    title: "How to Set Up & Stream IPTV on Samsung Smart TV | Teleview",
    description:
      "Complete installation guide for Samsung Smart TVs running Tizen OS. Install IBO Player or SmartOne IPTV directly from Samsung Apps with zero sideloading.",
    ogTitle: "IPTV on Samsung Smart TV: Tizen OS Setup Guide | Teleview",
    ogDescription:
      "Configure Teleview IPTV on Samsung Smart TVs: install verified apps from Samsung Smart Hub and activate M3U or Xtream API credentials online.",
    breadcrumbName: "Samsung Smart TV",
  },
  {
    path: "/devices/lg-smart-tv",
    indexable: true,
    rendering: "SSG",
    changefreq: "monthly",
    priority: 0.8,
    primaryIntent: "Informational How-To & Device Installation",
    primaryKeyword: "IPTV on LG Smart TV",
    secondaryTopics: [
      "LG webOS IPTV",
      "IBO Player LG TV",
      "SmartOne IPTV LG",
      "LG Content Store IPTV apps",
      "LG Magic Remote IPTV",
    ],
    h1: "How to Set Up & Stream IPTV on LG Smart TV",
    title: "How to Set Up & Stream IPTV on LG Smart TV (webOS) | Teleview",
    description:
      "Step-by-step setup guide for LG OLED, QNED, and NanoCell Smart TVs running webOS. Install IBO Player or SmartOne IPTV and enjoy 4K sports with Magic Remote.",
    ogTitle: "IPTV on LG Smart TV: webOS Installation Guide | Teleview",
    ogDescription:
      "Install IPTV apps on LG webOS Smart TVs directly from the LG Content Store. Connect Teleview credentials via web management portal.",
    breadcrumbName: "LG Smart TV",
  },
  {
    path: "/devices/android-tv",
    indexable: true,
    rendering: "SSG",
    changefreq: "monthly",
    priority: 0.8,
    primaryIntent: "Informational How-To & Device Installation",
    primaryKeyword: "IPTV on Android TV Box",
    secondaryTopics: [
      "Nvidia Shield IPTV",
      "Xiaomi Mi Box IPTV",
      "TiviMate Android TV",
      "Android TV box setup",
      "ExoPlayer hardware decoding",
    ],
    h1: "How to Set Up & Stream IPTV on Android TV Box",
    title: "How to Set Up & Stream IPTV on Android TV Box | Teleview",
    description:
      "Ultimate setup manual for Android TV boxes including Nvidia Shield TV, Xiaomi Mi Box, and Mecool. Configure TiviMate with Google Play Store installation.",
    ogTitle: "Android TV Box IPTV Setup Guide | Nvidia Shield & Mi Box",
    ogDescription:
      "Maximize your streaming quality on Android TV: install TiviMate or OTT Navigator, configure multi-screen viewing, and enable hardware 4K decoding.",
    breadcrumbName: "Android TV Box",
  },
  {
    path: "/devices/apple-tv",
    indexable: true,
    rendering: "SSG",
    changefreq: "monthly",
    priority: 0.8,
    primaryIntent: "Informational How-To & Device Installation",
    primaryKeyword: "IPTV on Apple TV",
    secondaryTopics: [
      "Apple TV 4K IPTV",
      "tvOS IPTV apps",
      "GSE Smart IPTV Apple TV",
      "Smarters Player Lite Apple",
      "AirPlay IPTV streaming",
    ],
    h1: "How to Set Up & Stream IPTV on Apple TV 4K",
    title: "How to Set Up & Stream IPTV on Apple TV 4K (tvOS) | Teleview",
    description:
      "High-performance IPTV guide for Apple TV 4K and tvOS. Install GSE Smart IPTV or Smarters Lite, sync EPG schedules, and use AirPlay from iPhone or iPad.",
    ogTitle: "IPTV on Apple TV 4K: tvOS Setup & Configuration Guide",
    ogDescription:
      "Experience fluid 60 FPS sports streaming on Apple TV 4K: install App Store players, connect Xtream Codes API, and enable HDR matching.",
    breadcrumbName: "Apple TV 4K",
  },
  {
    path: "/devices/roku",
    indexable: true,
    rendering: "SSG",
    changefreq: "monthly",
    priority: 0.8,
    primaryIntent: "Informational How-To & Device Installation",
    primaryKeyword: "IPTV on Roku",
    secondaryTopics: [
      "Roku IPTV streaming",
      "cast IPTV to Roku",
      "Roku screen mirroring",
      "Roku AirPlay IPTV",
      "Web Video Caster Roku",
    ],
    h1: "How to Stream IPTV on Roku Streaming Stick & TV",
    title: "How to Stream IPTV on Roku Streaming Stick & Roku TV | Teleview",
    description:
      "Understand IPTV limitations and proven casting methods for Roku devices. Stream Teleview using Apple AirPlay, Android screen casting, or Web Video Caster.",
    ogTitle: "IPTV on Roku: Screen Mirroring & Casting Guide | Teleview",
    ogDescription:
      "Learn how to stream live IPTV on Roku TVs and Streaming Sticks via AirPlay and screen mirroring without sideloading.",
    breadcrumbName: "Roku",
  },
  {
    path: "/devices/google-tv",
    indexable: true,
    rendering: "SSG",
    changefreq: "monthly",
    priority: 0.8,
    primaryIntent: "Informational How-To & Device Installation",
    primaryKeyword: "IPTV on Google TV",
    secondaryTopics: [
      "Chromecast with Google TV IPTV",
      "Google TV IPTV players",
      "sideload Google TV",
      "TiviMate Google TV",
      "Google TV Downloader",
    ],
    h1: "How to Set Up & Stream IPTV on Google TV & Chromecast",
    title: "How to Set Up & Stream IPTV on Google TV & Chromecast | Teleview",
    description:
      "Complete guide to streaming IPTV on Chromecast with Google TV and Sony/TCL Google TVs. Enable developer options, install TiviMate, and stream 4K live sports.",
    ogTitle: "Google TV IPTV Setup: Chromecast & Smart TV Guide | Teleview",
    ogDescription:
      "Step-by-step Google TV setup: unlock developer mode, install Downloader, configure TiviMate, and enjoy seamless voice search integration.",
    breadcrumbName: "Google TV",
  },
  {
    path: "/devices/formuler",
    indexable: true,
    rendering: "SSG",
    changefreq: "monthly",
    priority: 0.8,
    primaryIntent: "Informational How-To & Device Installation",
    primaryKeyword: "IPTV on Formuler",
    secondaryTopics: [
      "Formuler Z11 Pro Max",
      "MYTVOnline3 setup",
      "MOL3 IPTV portal",
      "Formuler MAC address registration",
      "Formuler recording PVR",
    ],
    h1: "How to Set Up & Stream IPTV on Formuler Z-Series",
    title: "How to Set Up IPTV on Formuler (Z11 Pro Max / Z10) | Teleview",
    description:
      "Ultimate setup manual for Formuler Z11 Pro Max, Z10 Pro, and Z8 running MYTVOnline 2 & 3. Configure Stalker portals, Xtream API, and PVR USB recording.",
    ogTitle: "Formuler Z-Series IPTV Setup: MYTVOnline3 Guide | Teleview",
    ogDescription:
      "Configure MYTVOnline 2/3 on Formuler set-top boxes: connect portals, map EPG schedules, and configure hardware timeshifting and recording.",
    breadcrumbName: "Formuler Z-Series",
  },
  {
    path: "/help-center/buffering",
    indexable: true,
    rendering: "SSG",
    changefreq: "monthly",
    priority: 0.8,
    primaryIntent: "Troubleshooting How-To & Performance Optimization",
    primaryKeyword: "how to stop IPTV buffering",
    secondaryTopics: [
      "IPTV freezing fix",
      "IPTV buffer size settings",
      "ISP throttling IPTV",
      "VPN for IPTV buffering",
      "5GHz Wi-Fi IPTV",
    ],
    h1: "How to Stop IPTV Buffering & Freezing: 2026 Diagnostic Guide",
    title: "How to Stop IPTV Buffering & Freezing (2026 Guide) | Teleview",
    description:
      "Stop IPTV buffering and stream loops immediately. Learn 4 proven fixes: 5 GHz Wi-Fi / Ethernet switching, VPN throttling bypass, and player buffer cache adjustments.",
    ogTitle: "How to Stop IPTV Buffering: Proven Solutions | Teleview",
    ogDescription:
      "Eliminate stream buffering during live sports matches with our technical diagnostic guide covering buffer caches, VPNs, and router settings.",
    breadcrumbName: "Fix Buffering",
  },
  {
    path: "/help-center/not-working",
    indexable: true,
    rendering: "SSG",
    changefreq: "monthly",
    priority: 0.8,
    primaryIntent: "Troubleshooting How-To & Service Restoration",
    primaryKeyword: "IPTV not working",
    secondaryTopics: [
      "IPTV service outage",
      "IPTV black screen",
      "HTTP 401 error IPTV",
      "HTTP 403 error IPTV",
      "IPTV credentials expired",
    ],
    h1: "IPTV Not Working? Master Diagnostic Checklist & Solutions",
    title: "IPTV Not Working? Master Diagnostic Checklist & Fixes | Teleview",
    description:
      "Step-by-step diagnostic checklist when your IPTV service stops playing. Resolve HTTP 401/403 errors, account expiration, DNS blocks, and app crashes.",
    ogTitle: "IPTV Not Working: Step-by-Step Diagnostic Manual | Teleview",
    ogDescription:
      "Restore your IPTV stream in minutes with our master diagnostic checklist for credential verification, DNS blocks, and network handshake errors.",
    breadcrumbName: "IPTV Not Working",
  },
  {
    path: "/help-center/epg-not-working",
    indexable: true,
    rendering: "SSG",
    changefreq: "monthly",
    priority: 0.8,
    primaryIntent: "Troubleshooting How-To & EPG Synchronization",
    primaryKeyword: "IPTV EPG not working",
    secondaryTopics: [
      "IPTV TV guide no information",
      "XMLTV EPG refresh",
      "TiviMate EPG update",
      "IPTV EPG time offset",
      "clear EPG cache",
    ],
    h1: "How to Fix IPTV EPG (Electronic Program Guide) Not Loading",
    title: "How to Fix IPTV EPG Not Loading & 'No Information' | Teleview",
    description:
      "Troubleshoot missing TV guide listings and 'No Information' errors in TiviMate, Smarters, and Smart TV players. Force EPG sync and correct time offsets.",
    ogTitle: "Fix IPTV EPG Not Working: TV Guide Sync Manual | Teleview",
    ogDescription:
      "Resolve missing TV guides, blank EPG grids, and incorrect schedule times with our technical EPG synchronization and cache guide.",
    breadcrumbName: "Fix EPG",
  },
  {
    path: "/help-center/channels-not-loading",
    indexable: true,
    rendering: "SSG",
    changefreq: "monthly",
    priority: 0.8,
    primaryIntent: "Troubleshooting How-To & Playlist Resolution",
    primaryKeyword: "IPTV channels not loading",
    secondaryTopics: [
      "IPTV playlist download failed",
      "IPTV spinning wheel",
      "Xtream API vs M3U",
      "router firewall blocking IPTV",
      "IPTV category loading error",
    ],
    h1: "How to Fix IPTV Channels & Playlists Not Loading",
    title: "How to Fix IPTV Channels & Playlists Not Loading | Teleview",
    description:
      "Resolve infinite spinning wheels, failed playlist downloads, and missing channel categories. Switch to Xtream Codes API and disable router firewall blocks.",
    ogTitle: "Fix IPTV Channels Not Loading: Step-by-Step Guide | Teleview",
    ogDescription:
      "Discover why IPTV channel categories fail to load and how to fix M3U memory bottlenecks, router security filters, and video codec conflicts.",
    breadcrumbName: "Channels Not Loading",
  },
  {
    path: "/help-center/connection-problems",
    indexable: true,
    rendering: "SSG",
    changefreq: "monthly",
    priority: 0.8,
    primaryIntent: "Troubleshooting How-To & Network Diagnostics",
    primaryKeyword: "IPTV connection problems",
    secondaryTopics: [
      "IPTV server connection failed",
      "cannot connect to IPTV server",
      "IPTV network timeout",
      "IPTV TLS SSL handshake",
      "SIP ALG router IPTV",
    ],
    h1: "How to Fix IPTV Connection Errors & Server Timeouts",
    title: "How to Fix IPTV Connection Errors & Server Timeouts | Teleview",
    description:
      "Diagnose and resolve 'Cannot Connect to Server' and network timeout errors. Flush router NAT tables, switch to public DNS, and bypass ISP port blocks.",
    ogTitle: "Fix IPTV Connection Problems & Network Timeouts | Teleview",
    ogDescription:
      "Technical troubleshooting for IPTV network timeouts, router packet dropping, TLS handshake failures, and port filtering.",
    breadcrumbName: "Connection Problems",
  },
  {
    path: "/help-center/internet-speed",
    indexable: true,
    rendering: "SSG",
    changefreq: "monthly",
    priority: 0.8,
    primaryIntent: "Informational How-To & Bandwidth Optimization",
    primaryKeyword: "internet speed for IPTV",
    secondaryTopics: [
      "minimum internet speed IPTV",
      "4K IPTV bandwidth requirement",
      "IPTV ping and jitter",
      "speed test for IPTV",
      "Ethernet vs Wi-Fi IPTV",
    ],
    h1: "Internet Speed Requirements for 4K IPTV Streaming",
    title: "Internet Speed Requirements for 4K IPTV Streaming (2026) | Teleview",
    description:
      "Learn recommended internet bandwidth, latency, and packet jitter for buffer-free 4K live sports and HD entertainment. Optimize Wi-Fi and test connection quality.",
    ogTitle: "Internet Speed Requirements for 4K IPTV | Teleview Guide",
    ogDescription:
      "Detailed bandwidth standards for SD, HD, and 4K 60 FPS streaming: understanding ping, packet jitter, and router QoS prioritization.",
    breadcrumbName: "Internet Speed",
  },
  {
    path: "/404",
    indexable: false,
    rendering: "SSG",
    primaryIntent: "Error Not Found",
    primaryKeyword: "page not found",
    secondaryTopics: ["404 error", "broken link navigation"],
    h1: "Page Not Found",
    title: "404 Not Found | Teleview",
    description: "The requested page could not be found.",
    ogTitle: "404 Not Found | Teleview",
    ogDescription: "The requested page could not be found.",
    breadcrumbName: "404",
  },
];

export const indexableRoutes = routes.filter((r) => r.indexable);
export const prerenderRoutes = routes.filter((r) => r.rendering === "SSG");

